services:
  mlflow:
    image: mlflow:latest
    command: mlflow server --backend-store-uri sqlite:///mlflow.db --default-artifact-root ./artifacts
    ports:
      - "5000:5000"
    volumes:
      - ./mlruns:/mlflow/mlruns
    environment:
      - MLFLOW_TRACKING_URI=sqlite:///mlflow.db

  inference:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    volumes:
      - ./data:/app/data
    depends_on:
      - mlflow